import requests
import json

def generate_ai_advice(crop, disease, weather_summary):
    """
    Generate AI-based agricultural advice using local LLaMA 3 (via Ollama).
    """

    prompt = f"""
You are an experienced agricultural expert.

A farmer has a crop currently affected by {disease}.
The current weather is described as {weather_summary}.

Provide short, practical, and clear advice including:
1️⃣ Likely cause
2️⃣ Recommended treatment
3️⃣ Preventive measures

Use a friendly but professional tone.
if the crop is healthy ignore the points of likely cause ,treatment and preventive measures.
and go straight to appreciate the condition of the crops and and give the farmer
 tips to keep the crops in that good condition.
    """

    try:
        response = requests.post(
            "http://127.0.0.1:11434/api/generate",
            json={
                "model": "llama3",
                "prompt": prompt,
                "stream": True  # ✅ Streaming mode
            },
            stream=True,
            timeout=120
        )

        response.raise_for_status()

        # Read each line of streaming JSON safely
        full_text = ""
        for line in response.iter_lines():
            if not line:
                continue
            try:
                data = json.loads(line.decode("utf-8"))
                full_text += data.get("response", "")
                if data.get("done", False):
                    break
            except json.JSONDecodeError:
                continue

        return full_text.strip() or "No advice generated by AI."

    except requests.exceptions.RequestException as e:
        return f"⚠️ Error connecting to LLaMA: {str(e)}"
    except Exception as e:
        return f"💥 Unexpected error: {str(e)}"
